// <auto-generated />
using System;
using HotelReservationSystemBackend.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelReservationSystemBackend.Data.Migrations
{
    [DbContext(typeof(HotelReservationContext))]
    [Migration("20240423062144_AddSeederForAdminUser")]
    partial class AddSeederForAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelReservationSystemBackend.Model.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoomNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Allocation", (string)null);
                });

            modelBuilder.Entity("HotelReservationSystemBackend.Model.BookingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalRent")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BookingRequest", (string)null);
                });

            modelBuilder.Entity("HotelReservationSystemBackend.Model.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePaths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NoOfRooms")
                        .HasColumnType("int");

                    b.Property<int>("RentPerDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hotel", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f29f30d-79da-4058-aa33-84bb1d9de6a4"),
                            ImagePaths = "[]",
                            Name = "Royal hotel",
                            NoOfRooms = 50,
                            RentPerDay = 5000
                        },
                        new
                        {
                            Id = new Guid("f07a50ba-f3f0-41e1-92cd-748174d33f76"),
                            ImagePaths = "[]",
                            Name = "Five star hotel",
                            NoOfRooms = 70,
                            RentPerDay = 4000
                        });
                });

            modelBuilder.Entity("HotelReservationSystemBackend.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Cnic")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("beba5d2b-ae7e-403d-8c00-f918489c2bcc"),
                            Age = 26,
                            Cnic = "33293-5749302-1",
                            Email = "aslamazhar@gmail.com",
                            Gender = 0,
                            Name = "Aslam Azhar",
                            Password = "aslam1234",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("4660b767-a47a-49e3-8952-365275188cd9"),
                            Age = 30,
                            Cnic = "33889-170293-3",
                            Email = "admin@gmail.com",
                            Gender = 0,
                            Name = "Admin",
                            Password = "Admin123",
                            Role = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
